### ISSUE TITLE
No module named 'distributions'

### ISSUE THREAD

**Issue by kemojal** [hackl/pyre#3]
When i import pyre in my project i got the following erro
 line 21, in <module>
   ` from distributions import *`
ModuleNotFoundError: No module named '`distributions`'

**Comment by hackl** [comment]
This error occurred by using pyre with Python 3.X. I updated the module to the new Python version. Now, this error should no longer appear.

**Comment by Jungle-13** [comment]
Sir,When i import pyre in my project i got the following erro

 import pystra
ModuleNotFoundError: No module named 'distributions'No module named 'pystra'
