### ISSUE TITLE
Generate alpha vector 

### ISSUE THREAD

**Issue by Florissijb** [hackl/pyre#5]
Hi all,

I am currently using pyre and have been able to successfully calculate the probability of failure with the FORM analysis. However, when I try to calculate and print the alphavector it prints "None". 

To print the alpha vector I used the following code: 

 alpha_vector = Analysis.computeAlpha()
 print("The alpha vector is given by {}".format(alpha_vector))

Result:
The alpha vector is given by None

**Comment by hackl** [comment]
I generated a function which returns the alpha vector for the FORM analysis.

```python
alpha_vector = Analysis.getAlpha()
```

**Comment by Florissijb** [comment]
It tells me that it doesn't have a function which does that?

Traceback (most recent call last):
  File "C:/Users/908698/PycharmProjects/Probabilistic/PROB_armourDW.py", line 60, in <module>
    main()
  File "C:/Users/908698/PycharmProjects/Probabilistic/PROB_armourDW.py", line 52, in main
    alpha_vector = Analysis.getAlpha()
AttributeError: 'Form' object has no attribute 'getAlpha'

**Comment by Florissijb** [comment]
I solved it, made a getAlpha function myself. Thanks for the help !
